### PR TITLE
Release V2

### PR DESCRIPTION
**Pull request by JLefebvre55**
Individual backend API route files
Login session management with a Redis store
EJS layouts, partials, and dynamic/conditional page rendering
Full API documentation

### CODE REVIEW

**Review by harsimrat99 — CHANGES_REQUESTED** [review]
Hello Jayden,

Thank you for asking for my review. I have skimmed through the codebase and I believe it looks great. Before we deploy it to AWS, I wanted to share some of the stuff that is being done on the actual server that is not on the repositories yet. It is primarily regarding the SSL certificates and the database connections.

We have to add some minor fixes for the codebase to incorporate the SSL certificates. Additionally, I already have some code on the server side that can redirect HTTP requests to HTTPS.

Please let me know your thoughts and I can help with what needs to be done in our next meeting.

**Review by harsimrat99 — CHANGES_REQUESTED** [review]
Hello Jayden,
Before merging the branch into staging, I suggest that we wait until Ian is finished with the forum post functionality. I am emphasizing this so that before we push stuff to staging we do not have an unfinished feature. I believe once at least the forum functionality is completed we should be okay to go with this merge. Please let me know if there are any concerns.

**Comment by JLefebvre55** [comment]
Sounds good. @iWebster28 make a new branch off of staging for the "new post" page/feature

**Review by harsimrat99 — APPROVED** [review]
Hello Jayden,
I have checked that the latest commits from staging will be merged into the master branch. Please proceed with merging the branches and closing this pull request.

**Pull request merged**
